name: Deploy Frontend to Staging

on:
  push:
    branches:
      - staging  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@v1
      with:
        flyctl_version: "latest"

    - name: Fly.io Deploy Frontend
      run: |
        flyctl auth login --access-token ${{ secrets.FLY_API_TOKEN_FRONTEND }}
        flyctl deploy --config fly.staging.toml -a psicontrol-front-staging
